export const ERROR_CODES = {
    UNKNOWN: 'E-UNKNOWN',
    NOT_FOUND: 'E-RESOURCE_NOT_FOUND',
    BAD_REQUEST: 'E-BAD_REQUEST',
    EMPTY_RESPONSE: 'E-EMPTY_PAYLOAD',
    USER_REGISTER_FAIL: 'E-FIREBASE-PHONE-MISMATCH',
    INVALID_PLAYER_LIST: 'E-INVALID_PLAYER_LIST',
    MISSING_PLAYER_PERFORMANCES: 'E-MISSING_PLAYER_PERFORMANCE',
    UNAUTHORIZED_1: 'E-UNAUTHORIZED-1', // Token missing
    UNAUTHORIZED_2: 'E-UNAUTHORIZED-2', // Token expired
    UNAUTHORIZED_3: 'E-UNAUTHORIZED-3', // Unhandled Auth Error
    UNAUTHORIZED_4: 'E-UNAUTHORIZED-4', // Token invalid
  };
  